### ISSUE TITLE
set_difference problem

### ISSUE THREAD

**Issue by zzxxxl** [boyiwei/alignment-attribution-code#2]
I used align_short and p(0.01) for valuing top2down/down2top wandg pruning, it gets the similar results like the paper, but when I use the pkl to run the set_difference, it's went wrong:
<img width="441" alt="image" src="https://github.com/boyiwei/alignment-attribution-code/assets/103178086/cff2178c-935e-48b8-9c8e-842337daa909">
i tried to make W_metric the negative sign, and it looked like getting a good result:
<img width="443" alt="image" src="https://github.com/boyiwei/alignment-attribution-code/assets/103178086/3afffae2-059a-4e9a-b615-52dc408162e4">
I made the experiment for several times and it conducts the same results. Could anyone offer me a favor?

**Comment by zzxxxl** [comment]
When I made safe/utility pkl, I used --neg_prune to get the top score.

**Comment by boyiwei** [comment]
Hi, could you provide the script you are using in order to reproduce the problem? What is the meaning of "make W_metric the negative sign"? Thanks!

**Comment by boyiwei** [comment]
In the paper we are presenting the results with align, not align_short. If you are still encountering the problem with align dataset, please let me know. Thanks!

**Comment by zzxxxl** [comment]
> Hi, could you provide the script you are using in order to reproduce the problem? What is the meaning of "make W_metric the negative sign"? Thanks!
I just use this script to get the top safety neuron:
model="llama2-7b-chat-hf"
method="wandg"
type="unstructured"
suffix="weightonly"
save_dir="out/$model/safe_wandg_short/"

nohup python main.py \
    --model $model \
    --prune_method $method \
    --prune_data align_short \
    --sparsity_ratio 0.5 \
    --sparsity_type $type \
    --neg_prune \
    --save $save_dir \
    --eval_zero_shot \
    --eval_attack \
    --dump_wanda_score \
    --save_attack_res \
    > output_safe_wandg_short.txt 2>&1 &
And similar script to get the utility neuron pkl file, but when I made the set_difference like this:
#!/bin/bash
model="llama2-7b-chat-hf"
method="wandg_set_difference"
type="unstructured"
suffix="weightonly"
save_dir="out/llama2-7b-chat-hf/safe_utility_004_002_div"

nohup python main.py \
    --model $model \
    --prune_method $method \
    --sparsity_ratio 0.5 \
    --prune_data align_short \
    --p 0.04\
    --q 0.02\
    --sparsity_type $type \
    --save $save_dir \
    --eval_zero_shot \
    --eval_attack \
    --save_attack_res \
    > safe_utility_difference_004_002_div.txt 2>&1 &
  It's presents the result in Picture 1 in the first question above,but when I just took the negative sign when reading W_metric1 and W_metric2 in prune.py/prune_set_difference:
<img width="778" alt="image" src="https://github.com/boyiwei/alignment-attribution-code/assets/103178086/5d6c0e40-7b0b-4444-894b-9d26db2b8e79">
I got the result in Picture 2 in the first question above, In the process I just made change to the model save path and pkl save path and didn't change any logical function of the code.Thanks for your kindly help!

**Comment by boyiwei** [comment]
What is your metric1 and metric2?

**Comment by zzxxxl** [comment]
Metric1 is utility, and metric2 is safety. Thanks~

**Comment by boyiwei** [comment]
Did you observe the same phenomenon when p>q but different values?

**Comment by boyiwei** [comment]
My hyperparameter search is based on "align" dataset, not "Align-short" dataset. I would recommend you try more combinations, if you observe similar phenomena for all the cases, please let me know. Thanks!

**Comment by zzxxxl** [comment]
This is part of result of the grid search:
https://github.com/boyiwei/alignment-attribution-code/issues/2#issuecomment-2078478548
I used the "align" dataset for set_difference and it got the similar result like "align_short", Just  a slight difference in the result. Maybe I need to reproduce the code one more time. Thanks for your help!

**Comment by zzxxxl** [comment]
This is part of result of the grid search:
![Uploading image.png…]()
I used the "align" dataset for set_difference and it got the similar result like "align_short", Just a slight difference in the result data. Maybe I need to reproduce the code one more time. Thanks for your help!

**Comment by zzxxxl** [comment]
This is part of result of the grid search:
<img width="441" alt="image" src="https://github.com/boyiwei/alignment-attribution-code/assets/103178086/d2197404-c248-41a0-8a80-0217ea3c84e9">
I used the "align" dataset for set_difference and it got the similar result like "align_short", Just a slight difference in the result data. Maybe I need to reproduce the code one more time. Thanks for your help!

**Comment by boyiwei** [comment]
What is the corresponding meaning of the list of values? If I don't understand wrong, you can observe a significantly high ASR when p=0.06, q=0.04/0.05, which aligns with our experimental results. If the difference between p and q is large, it is normal that the model is not jailbroken.

**Comment by zzxxxl** [comment]
Yes! You are right. I think I need to reproduce the code for serveral times to check if there is any error I make.Thank you for your help! I'll reach out to you if there is any problem! Tks once again!

**Comment by jeffreyzhanghc** [comment]
the metric1 should be alpaca_cleaned_no_safety to search for utility and metric2 use align to search for safety right?

**Comment by boyiwei** [comment]
> the metric1 should be alpaca_cleaned_no_safety to search for utility and metric2 use align to search for safety right?

Yes.

**Comment by jeffreyzhanghc** [comment]
thanks for quick response, so should I run prune_wanda first to get W_metric for safety and utility? since I see there is a fixed W_metric loading in prune set difference
<img width="856" alt="image" src="https://github.com/user-attachments/assets/c6d7f300-72e7-4f0a-afb2-8442ba60cb91">

**Comment by boyiwei** [comment]
> thanks for quick response, so should I run prune_wanda first to get W_metric for safety and utility? since I see there is a fixed W_metric loading in prune set difference <img alt="image" width="856" src="https://private-user-images.githubusercontent.com/98052564/362103499-c6d7f300-72e7-4f0a-afb2-8442ba60cb91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTQxNDksIm5iZiI6MTcyNDgxMzg0OSwicGF0aCI6Ii85ODA1MjU2NC8zNjIxMDM0OTktYzZkN2YzMDAtNzJlNy00ZjBhLWFmYjItODQ0MmJhNjBjYjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAyNTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZWM4YTFiNGQxZjVlOGYxNTVmNDMwY2RlNjkyYmRhZDcxODY0MTkzY2Y5YTU2N2I2NDQzOTljNjU0MTRkZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s5WXahq3lcKYpUET3GQxqGu-_A9ICYZMyQSwkrdSOIU">

Yes you should first dump the importance score either with wanda or SNIP (wandg in the code), then apply the code you mentioned to compute the set difference. See here: https://github.com/boyiwei/alignment-attribution-code?tab=readme-ov-file#23-wandasnip-score-dumping

**Comment by jeffreyzhanghc** [comment]
Really appreciate. I am exploring the jailbreak's effect on safety-critical tensor along and try to compare activation before/after the attack. Which part of code do you best recommend to use as track for safety neurons. 
<img width="769" alt="image" src="https://github.com/user-attachments/assets/500e28c8-f2ed-42f3-a152-936478b7757b">
My thought will be simply use filtered_index_rows&columns to index the isolate and extract safety neuron if I understand correctly

**Comment by boyiwei** [comment]
> Really appreciate. I am exploring the jailbreak's effect on safety-critical tensor along and try to compare activation before/after the attack. Which part of code do you best recommend to use as track for safety neurons. <img alt="image" width="769" src="https://private-user-images.githubusercontent.com/98052564/362105456-500e28c8-f2ed-42f3-a152-936478b7757b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MTQ4MjksIm5iZiI6MTcyNDgxNDUyOSwicGF0aCI6Ii85ODA1MjU2NC8zNjIxMDU0NTYtNTAwZTI4YzgtZjJlZC00MmYzLWExNTItOTM2NDc4Yjc3NTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAzMDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZmUwZTE3NTAxZGUwNjc4ZTAyMTVjM2YzZTQxZmIwODdjY2E0NWEyYmI4ZjEzNTI2MDZjYzQ5Mjk5MzMyMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NP60nEabBM8h-ozM-R3PvmlJ1wAv_xQHEyGksWK8BHo"> My thought will be simply use filtered_index_rows&columns to index the isolate and extract safety neuron if I understand correctly

Theoretically, once you dump the importance score you will know how the neurons are activated across all weight metrics. Our code basically tries to isolate the neurons that have a high safety score but a low utility score (which we believe only contributes to the model's safety alignment). Of course you can apply your self-defined filter to get the neurons that align with your purposes.

**Comment by jeffreyzhanghc** [comment]
Thanks. If I understand correctly the prune_wandg_set_difference is specfically sued for separating neurons with high safety score but a low utility score, so I can use --save_mask to track the mask and hence know the neurons that has relatively high safety while low utility. 
<img width="969" alt="image" src="https://github.com/user-attachments/assets/b791eab4-7bd6-4dc9-9577-b26b80bf8dbc">

Plus, since mask records many layer, I saw many middle layers having with all True. 
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/fdc247cb-7bf4-4374-9330-d829f52af5f8">
So does this imply that I should focus more on lm_head layer?

**Comment by boyiwei** [comment]
I don't fully understand what is the meaning of "True" in your code. Both attention layer and NLP layer has entanglement between safety and utility. We did an analysis in Sec4.3

**Comment by stha-prashant** [comment]
I actually got similar results as @zzxxxl. When I do set difference as provided in the code. I get very small ASR and sparsity level, much lower than reported int he paper. 

method	actual_sparsity	p	q	metric	score
wandg_set_difference	0.000327	0.04	0.02	PPL	6.4936
wandg_set_difference	0.000327	0.04	0.02	inst_ASR_basic	0.0000
wandg_set_difference	0.000327	0.04	0.02	inst_ASR_basic_nosys	0.0000
wandg_set_difference	0.000327	0.04	0.02	inst_ASR_multiple_nosys	0.0540
wandg_set_difference	0.000327	0.04	0.02	no_inst_ASR_basic	0.0400
wandg_set_difference	0.000327	0.04	0.02	no_inst_ASR_basic_nosys	0.1700
wandg_set_difference	0.000327	0.04	0.02	no_inst_ASR_multiple_nosys	0.2360
wandg_set_difference	0.000327	0.04	0.02	ASR_gcg	0.0900
wandg_set_difference	0.000327	0.04	0.02	hellaswag	0.5650
wandg_set_difference	0.000327	0.04	0.02	winogrande	0.6550
wandg_set_difference	0.000327	0.04	0.02	arc_challenge	0.4350
wandg_set_difference	0.000327	0.04	0.02	boolq	0.7900
wandg_set_difference	0.000327	0.04	0.02	openbookqa	0.3300
wandg_set_difference	0.000327	0.04	0.02	rte	0.7200
wandg_set_difference	0.000327	0.04	0.02	averaged	0.5825


But when i set invert the ordering during top k selection by doing -W_metric instead of W_metric, I get expected sparsity level and high ASR as in the paper:


wandg_set_difference	0.007673	0.04	0.02	PPL	7.6400
wandg_set_difference	0.007673	0.04	0.02	inst_ASR_basic	0.1100
wandg_set_difference	0.007673	0.04	0.02	inst_ASR_basic_nosys	0.7300
wandg_set_difference	0.007673	0.04	0.02	inst_ASR_multiple_nosys	0.6960
wandg_set_difference	0.007673	0.04	0.02	no_inst_ASR_basic	0.5400
wandg_set_difference	0.007673	0.04	0.02	no_inst_ASR_basic_nosys	0.9200
wandg_set_difference	0.007673	0.04	0.02	no_inst_ASR_multiple_nosys	0.8940
wandg_set_difference	0.007673	0.04	0.02	ASR_gcg	0.9800
wandg_set_difference	0.007673	0.04	0.02	winogrande	0.6800
wandg_set_difference	0.007673	0.04	0.02	rte	0.6850
wandg_set_difference	0.007673	0.04	0.02	boolq	0.8050
wandg_set_difference	0.007673	0.04	0.02	hellaswag	0.5350
wandg_set_difference	0.007673	0.04	0.02	openbookqa	0.3200
wandg_set_difference	0.007673	0.04	0.02	arc_challenge	0.4100
wandg_set_difference	0.007673	0.04	0.02	averaged	0.5725


 I used --neg_prune to get the initial score dumps which gave the wrong ordering.
So the fix for this low sparsity and low ASR issue is just to avoid using --neg_prune during the initial score dump if anyone else is running into this issue.
