### ISSUE TITLE
Can This Method Be Transferred to Other Models Like Llama3?

### ISSUE THREAD

**Issue by XEric7** [boyiwei/alignment-attribution-code#7]
The ActSVD (orthogonal projection) method (3.3: Remove rank with orthogonal projection) performs exceptionally well on Llama2. However, when I applied it to Llama3, the results dropped significantly. 

I made the following adjustments when I transfer your method to Llama3:
- Skipped modifying the 𝐾 and 𝑉 projection matrices in the attention block, as their shapes are much smaller compared to other matrices because Llama3 use Grouped Query.
- Used Llama3 to generate SFT data responses, replacing those in [SFT_aligned_llama2-7b-chat-hf_train.csv](https://github.com/boyiwei/alignment-attribution-code/blob/main/data/SFT_aligned_llama2-7b-chat-hf_train.csv), and adjusted the prompts to align with Llama3's chat format.

For the experiment, I used the default hyperparameters (𝑟𝑢=3000,𝑟𝑠=4000).
I'm unsure why the performance dropped so significantly. Could the changes I made have significantly disrupted the effectiveness of the method? Or should I consider adjusting the hyperparameters(𝑟𝑢 and 𝑟𝑠). If I need to adjust the hyperparameters, are there any methods or guidelines I can follow to optimize them?

**Comment by boyiwei** [comment]
Hi, we didn't do any experiments for the Llama3 model, but we believe the method can be transferred to Llama3. The optimal ru and rs are different with different models, so you should do hyperparameter search instead of directly using the one that works in the Llama2 model. In our experiments, we just did the grid search, but you can try some tricks like Bayesian optimization.
